### ISSUE TITLE
Clarification of Makefile from Line 15 to 17 

### ISSUE THREAD

**Issue by maxiaodage** [darinpeetz/TopOpt3D#1]
#DEPEND = mpicxx -isystem${MYLIB_DIR}/Eigen -isystem${SLEPC_DIR}/include \
          -isystem${SLEPC_DIR}/${PETSC_ARCH}/include -isystem${PETSC_DIR}/include \
          -isystem${PETSC_DIR}/${PETSC_ARCH}/include

Why these are partially commented out?

**Comment by darinpeetz** [comment]
It's not partially commented, note the line continuation characters "\\". That entire block is commented.
